version: "3.8"

services:
  envoy:
    image: docker.io/envoyproxy/envoy-debug:v1.33.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - dnsserver
      - httpserver
    command: 
      - "envoy"
      - "-c"
      - "/etc/envoy/envoy.yaml"
      - "--log-level"
      - "warning"
      - "--component-log-level"
      - "dns:debug"
    security_opt:
      - "label=disable" # required for OSX podman at least
    networks:
      custom_network:
        ipv4_address: 172.16.238.150

  dnsserver:
    image: docker.io/library/python:3.13
    environment:
      PYTHONUNBUFFERED: "1"
    working_dir: /code
    command:
      - python3
      - dns_server.py
    volumes:
      - ./:/code
    networks:
      custom_network:
        ipv4_address: 172.16.238.200

  httpserver:
    image: docker.io/library/python:3.13
    environment:
      PYTHONUNBUFFERED: "1"
    working_dir: /code
    command:
      - python3
      - http_server.py
      - "8080"
    volumes:
      - ./:/code
    networks:
      custom_network:
        ipv4_address: 172.16.238.100
  
  httpcaller:
    image: docker.io/library/python:3.13
    environment:
      PYTHONUNBUFFERED: "1"
    working_dir: /code
    command:
      - python3
      - http_caller.py
      - "http://172.16.238.150:8080"
    volumes:
      - ./:/code
    depends_on:
      - envoy
    networks:
      custom_network:
        ipv4_address: 172.16.238.160

networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.16.238.0/24

